GRANT CONNECT ON DATABASE banking_system TO user_test;

GRANT USAGE ON SCHEMA public TO user_test;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_test;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO user_test;